# ══════════════════════════════════════════════════════════════════════
# 250 COCO-aligned Image Scenarios
# Every primary object in every prompt is one of the 80 COCO categories:
#   person, bicycle, car, motorcycle, airplane, bus, train, truck, boat,
#   traffic light, fire hydrant, stop sign, parking meter, bench, bird,
#   cat, dog, horse, sheep, cow, elephant, bear, zebra, giraffe,
#   backpack, umbrella, handbag, tie, suitcase, frisbee, skis, snowboard,
#   sports ball, kite, baseball bat, baseball glove, skateboard,
#   surfboard, tennis racket, bottle, wine glass, cup, fork, knife,
#   spoon, bowl, banana, apple, sandwich, orange, broccoli, carrot,
#   hot dog, pizza, donut, cake, chair, couch, potted plant, bed,
#   dining table, toilet, tv, laptop, mouse, remote, keyboard,
#   cell phone, microwave, oven, toaster, sink, refrigerator, book,
#   clock, vase, scissors, teddy bear, hair drier, toothbrush.
# Scene elements (walls, trees, kitchens, parks) appear only as context,
# never as bounding-box subjects.
# ══════════════════════════════════════════════════════════════════════


SCENARIOS = [
    # ── People & Activities (30) ───────────────────────────────────────
    {"name": "dog_bench",               "prompt": "A dog sitting on a bench in a park"},
    {"name": "cats_couch",              "prompt": "Two cats playing with a sports ball on a couch"},
    {"name": "person_coffee",           "prompt": "A person holding a cup at a dining table"},
    {"name": "books_lamp",              "prompt": "A book and a vase on a dining table"},
    {"name": "bicycle_alley",           "prompt": "A bicycle leaning against a wall in an alley"},
    {"name": "bird_potted_plant",       "prompt": "A bird perched on a potted plant on a balcony"},
    {"name": "car_house",               "prompt": "A blue car parked in front of a house"},
    {"name": "plate_fork_knife",        "prompt": "A pizza on a plate with a fork and a knife on a dining table"},
    {"name": "backpack_chair",          "prompt": "A backpack on a chair in a bedroom"},
    {"name": "people_laptops",          "prompt": "Two people at a dining table working on laptops"},
    {"name": "person_reading_couch",    "prompt": "A person reading a book on a couch"},
    {"name": "chef_knife_carrot",       "prompt": "A person chopping a carrot with a knife on a dining table"},
    {"name": "person_laptop_cup",       "prompt": "A person using a laptop next to a cup at a dining table"},
    {"name": "jogger_park",             "prompt": "A person jogging along a path in a park"},
    {"name": "person_umbrella",         "prompt": "A person holding an umbrella on a city sidewalk"},
    {"name": "child_sports_ball",       "prompt": "A child kicking a sports ball on a grassy field"},
    {"name": "person_cart_bottle",      "prompt": "A person pushing a shopping cart with a bottle in a grocery store"},
    {"name": "construction_worker",     "prompt": "A person in a hard hat standing near a truck at a construction site"},
    {"name": "person_bicycle_lane",     "prompt": "A person riding a bicycle on a road with cars nearby"},
    {"name": "surfer_beach",            "prompt": "A person carrying a surfboard on a sandy beach"},
    {"name": "hiker_backpack",          "prompt": "A person with a backpack walking on a mountain trail"},
    {"name": "person_tennis",           "prompt": "A person holding a tennis racket on a tennis court"},
    {"name": "skateboarder_ramp",       "prompt": "A person performing a trick on a skateboard at a skate park"},
    {"name": "couple_wine_glasses",     "prompt": "Two people at a dining table with wine glasses and a pizza"},
    {"name": "person_yoga_mat",         "prompt": "A person sitting on a mat in a bright living room"},
    {"name": "child_dog_yard",          "prompt": "A child playing with a dog and a frisbee in a backyard"},
    {"name": "photographer_street",     "prompt": "A person holding a camera on a city street"},
    {"name": "person_potted_plant",     "prompt": "A person kneeling next to a potted plant in a garden"},
    {"name": "waiter_tray",             "prompt": "A person carrying a tray with a wine glass in a restaurant"},
    {"name": "group_picnic",            "prompt": "Three people at a picnic with a bowl of fruit and a bottle on a blanket"},

    # ── Animals (20) ──────────────────────────────────────────────────
    {"name": "cat_window",              "prompt": "A cat sitting on a chair next to a window"},
    {"name": "dog_sports_ball",         "prompt": "A dog running with a sports ball in a backyard"},
    {"name": "horse_field",             "prompt": "A horse standing in an open green field"},
    {"name": "cow_barn",                "prompt": "A cow standing inside a barn"},
    {"name": "sheep_meadow",            "prompt": "Three sheep grazing in a green meadow"},
    {"name": "elephant_savanna",        "prompt": "An elephant walking across a savanna landscape"},
    {"name": "giraffe_field",           "prompt": "A giraffe standing in an open field"},
    {"name": "zebra_grass",             "prompt": "A zebra standing in tall grass"},
    {"name": "bear_forest",             "prompt": "A bear walking through a forest"},
    {"name": "birds_branches",          "prompt": "Two birds perched on a tree branch in a garden"},
    {"name": "cat_couch",               "prompt": "A cat sleeping on a couch"},
    {"name": "dog_car",                 "prompt": "A dog with its head out of a car window"},
    {"name": "bird_chair_indoors",      "prompt": "A colorful bird perched on the back of a chair indoors"},
    {"name": "horse_rider",             "prompt": "A person riding a horse on a dirt trail"},
    {"name": "birds_pond",              "prompt": "Two birds standing at the edge of a pond"},
    {"name": "person_dog_park",         "prompt": "A person walking a dog on a path in a park"},
    {"name": "cat_books",               "prompt": "A cat sitting next to a stack of books on a dining table"},
    {"name": "cow_pasture",             "prompt": "A cow grazing in a pasture with a fence in the background"},
    {"name": "dog_frisbee",             "prompt": "A dog catching a frisbee in mid-air in a park"},
    {"name": "bird_branch",             "prompt": "A bird perched on a branch with leaves around it"},

    # ── Vehicles & Transportation (20) ────────────────────────────────
    {"name": "bus_stop_people",         "prompt": "A bus stopped at a curb with two people waiting on the sidewalk"},
    {"name": "bicycles_rack",           "prompt": "Three bicycles parked together on a city sidewalk"},
    {"name": "motorcycle_garage",       "prompt": "A motorcycle parked next to a car in a garage"},
    {"name": "truck_highway",           "prompt": "A truck driving on a wide highway with a stop sign nearby"},
    {"name": "car_traffic_light",       "prompt": "A car stopped at a traffic light at an intersection"},
    {"name": "train_platform",          "prompt": "A train at a platform with two people boarding"},
    {"name": "airplane_runway",         "prompt": "An airplane on a runway at an airport"},
    {"name": "boat_harbor",             "prompt": "A boat moored next to another boat at a harbor dock"},
    {"name": "cars_intersection",       "prompt": "Two cars stopped at a red traffic light at a city intersection"},
    {"name": "school_bus",              "prompt": "A yellow bus parked in front of a school building"},
    {"name": "truck_street",            "prompt": "A truck driving on a city street next to a stop sign"},
    {"name": "fire_hydrant_sidewalk",   "prompt": "A red fire hydrant on a city sidewalk next to a parked car"},
    {"name": "bicycle_cafe",            "prompt": "A bicycle parked outside a cafe with a person at a chair"},
    {"name": "truck_residential",       "prompt": "A white truck parked on a residential street"},
    {"name": "boat_river",              "prompt": "A small boat on a calm river"},
    {"name": "car_road",                "prompt": "A car driving on a scenic coastal road"},
    {"name": "motorcycle_city",         "prompt": "A person riding a motorcycle on a busy city road"},
    {"name": "truck_warehouse",         "prompt": "A truck parked outside a large warehouse loading dock"},
    {"name": "car_wash_person",         "prompt": "A person washing a car in a driveway with a bucket"},
    {"name": "airplane_clouds",         "prompt": "An airplane flying through a sky filled with clouds"},

    # ── Kitchen & Food (25) ───────────────────────────────────────────
    {"name": "toaster_orange_bowl",     "prompt": "A toaster, an orange, and a bowl on a kitchen counter"},
    {"name": "pizza_table",             "prompt": "A pizza on a dining table with a bottle and two cups"},
    {"name": "sandwich_knife",          "prompt": "A sandwich on a dining table with a knife and an apple"},
    {"name": "cake_table",              "prompt": "A cake on a dining table with a fork and a cup"},
    {"name": "fruit_bowl_counter",      "prompt": "A bowl with apples, bananas, and oranges on a kitchen counter"},
    {"name": "bowl_chopsticks",         "prompt": "A bowl of food with a fork and a knife on a dining table"},
    {"name": "microwave_cup",           "prompt": "A microwave on a kitchen counter next to a cup"},
    {"name": "salad_bowl_fork",         "prompt": "A bowl of broccoli and carrots with a fork on a dining table"},
    {"name": "oven_kitchen",            "prompt": "An oven and a microwave in a home kitchen with a bowl on the counter"},
    {"name": "refrigerator_open",       "prompt": "An open refrigerator stocked with bottles and a bowl of fruit"},
    {"name": "wine_glasses_bottle",     "prompt": "Two wine glasses and a bottle on a dining table"},
    {"name": "person_oven_pizza",       "prompt": "A person putting a pizza into an oven in a kitchen"},
    {"name": "bowl_spoon_table",        "prompt": "A bowl of soup with a spoon on a dining table"},
    {"name": "donut_cup_counter",       "prompt": "A donut on a plate next to a cup of coffee on a counter"},
    {"name": "hot_dog_person",          "prompt": "A person holding a hot dog at an outdoor food stand"},
    {"name": "person_cup_street",       "prompt": "A person holding a cup standing on a sunny street"},
    {"name": "bowl_apples_table",       "prompt": "A bowl of apples and a knife on a dining table"},
    {"name": "fork_knife_plate",        "prompt": "A fork and a knife next to a sandwich on a dining table"},
    {"name": "donut_plate",             "prompt": "Three donuts on a plate next to a cup on a dining table"},
    {"name": "microwave_toaster",       "prompt": "A microwave and a toaster on a kitchen counter next to a cup"},
    {"name": "knife_carrots_board",     "prompt": "Carrots and broccoli with a knife on a dining table"},
    {"name": "bowl_pot_stove",          "prompt": "A bowl and a spoon on a counter next to an oven in a kitchen"},
    {"name": "cake_oven",               "prompt": "A cake on a dining table next to an oven in a kitchen"},
    {"name": "wine_glass_bottle_table", "prompt": "A wine glass and a bottle on a dining table"},
    {"name": "bowl_oranges_knife",      "prompt": "A bowl of oranges and a knife on a kitchen counter"},

    # ── Indoor & Furniture (20) ───────────────────────────────────────
    {"name": "couch_tv_living_room",    "prompt": "A couch with a tv on a stand and a potted plant in a living room"},
    {"name": "bed_clock",               "prompt": "A bed with pillows and a clock on a bedside table"},
    {"name": "desk_laptop_keyboard",    "prompt": "A desk with a laptop, a keyboard, and a mouse"},
    {"name": "sink_toothbrush_mirror",  "prompt": "A sink with a toothbrush and a cup on a bathroom counter"},
    {"name": "dining_table_setup",      "prompt": "A dining table with plates, wine glasses, and a bottle"},
    {"name": "chair_books",             "prompt": "An armchair next to a stack of books and a potted plant"},
    {"name": "chairs_classroom",        "prompt": "Three chairs and a dining table in a classroom"},
    {"name": "chairs_waiting",          "prompt": "Two chairs and a potted plant in a waiting area"},
    {"name": "chair_book_lamp",         "prompt": "A chair with a book and a clock on a side table"},
    {"name": "bed_teddy_bear",          "prompt": "A teddy bear on a bed in a child's bedroom"},
    {"name": "scissors_book_table",     "prompt": "Scissors, a book, and a cup on a dining table in a workshop"},
    {"name": "chairs_studio",           "prompt": "Two chairs and a potted plant in a yoga studio"},
    {"name": "chair_book_window",       "prompt": "A chair with a book on it next to a potted plant"},
    {"name": "kitchen_counter_setup",   "prompt": "A kitchen counter with a microwave, a toaster, and a bowl of fruit"},
    {"name": "couch_chairs_table",      "prompt": "A couch and two chairs around a dining table in a living room"},
    {"name": "office_chairs_table",     "prompt": "A dining table with three chairs and a laptop in an office"},
    {"name": "chair_couch_clock",       "prompt": "A couch and a chair next to a clock on a wall"},
    {"name": "chairs_balcony",          "prompt": "Two chairs and a potted plant on a balcony"},
    {"name": "chair_book_storage",      "prompt": "A chair with a book and a vase on a dining table"},
    {"name": "potted_plants_room",      "prompt": "Three potted plants on a dining table next to a chair"},

    # ── Sports & Recreation (25) ──────────────────────────────────────
    {"name": "person_sports_ball_field","prompt": "A person kicking a sports ball on a green field"},
    {"name": "person_sports_ball_court","prompt": "A person bouncing a sports ball on an outdoor court"},
    {"name": "person_pool",             "prompt": "A person swimming in a pool"},
    {"name": "person_baseball_bat",     "prompt": "A person holding a baseball bat at a baseball field"},
    {"name": "person_golf",             "prompt": "A person swinging a baseball bat on a golf course"},
    {"name": "person_skis",             "prompt": "A person on skis going down a snowy slope"},
    {"name": "people_sports_ball_beach","prompt": "Two people with a sports ball on a sandy beach"},
    {"name": "cyclists_road",           "prompt": "Three people on bicycles riding on a road"},
    {"name": "person_sports_ball_gym",  "prompt": "A person holding a sports ball in a gym"},
    {"name": "person_baseball_glove",   "prompt": "A person wearing a baseball glove on a green field"},
    {"name": "person_skateboard",       "prompt": "A person on a skateboard at a skate park"},
    {"name": "people_frisbee",          "prompt": "Two people throwing a frisbee in an open park"},
    {"name": "person_kite",             "prompt": "A person flying a kite on a sandy beach"},
    {"name": "people_tennis_racket",    "prompt": "Two people with tennis rackets on a tennis court"},
    {"name": "person_surfboard_water",  "prompt": "A person paddling on a surfboard in calm water"},
    {"name": "person_sports_ball_indoor","prompt": "A person holding a sports ball indoors near a chair"},
    {"name": "people_tennis_racket2",   "prompt": "Two people on opposite sides of a tennis court with rackets"},
    {"name": "person_baseball_bat2",    "prompt": "A person swinging a baseball bat on a green field"},
    {"name": "horse_person_track",      "prompt": "A person riding a horse on a dirt track"},
    {"name": "person_sports_ball_lane", "prompt": "A person rolling a sports ball down an indoor lane"},
    {"name": "person_skating",          "prompt": "A person skating on an indoor rink"},
    {"name": "person_snowboard",        "prompt": "A person on a snowboard on a snowy slope"},
    {"name": "person_boat_fishing",     "prompt": "A person on a boat holding a rod over the water"},
    {"name": "people_sports_ball_ring", "prompt": "Two people boxing in a ring with a sports ball nearby"},
    {"name": "people_marathon",         "prompt": "Three people running together on a city road"},

    # ── Outdoor & Nature (20) ─────────────────────────────────────────
    {"name": "bench_park_path",         "prompt": "A bench on a path in a park surrounded by greenery"},
    {"name": "umbrella_chair_beach",    "prompt": "An umbrella and a chair on a sandy beach"},
    {"name": "person_forest_path",      "prompt": "A person walking on a path through a forest"},
    {"name": "boat_lake",               "prompt": "A boat on a calm lake with mountains in the background"},
    {"name": "potted_plant_bench",      "prompt": "A potted plant next to a bench in a garden"},
    {"name": "person_river_bridge",     "prompt": "A person walking on a stone bridge over a river"},
    {"name": "truck_field",             "prompt": "A truck driving through a farm field"},
    {"name": "sheep_cottage",           "prompt": "Two sheep grazing in a field with a cottage in the background"},
    {"name": "boat_waterfall",          "prompt": "A small boat on water near a waterfall"},
    {"name": "potted_plants_sunset",    "prompt": "Three potted plants on a balcony at sunset"},
    {"name": "person_apple_tree",       "prompt": "A person reaching for an apple in an apple orchard"},
    {"name": "people_park_bench",       "prompt": "Two people on a bench in a park near a fountain"},
    {"name": "person_field",            "prompt": "A person standing in a field of sunflowers"},
    {"name": "potted_plant_desert",     "prompt": "A potted plant on a porch with a desert landscape behind"},
    {"name": "bench_park_autumn",       "prompt": "A bench on a path covered in colorful autumn leaves"},
    {"name": "person_cliff_ocean",      "prompt": "A person standing on a rocky cliff overlooking the ocean"},
    {"name": "potted_plant_field",      "prompt": "A potted plant on a wooden table in a lavender field"},
    {"name": "person_field_flowers",    "prompt": "A person walking through a field of colorful flowers"},
    {"name": "person_mountain",         "prompt": "A person standing on a snowy mountain peak"},
    {"name": "person_walkway_swamp",    "prompt": "A person walking on a wooden walkway through a swamp"},

    # ── Market & Store (20) ───────────────────────────────────────────
    {"name": "store_bottles_shelf",     "prompt": "A grocery store aisle with bottles on shelves and a person with a cart"},
    {"name": "vase_flowers_market",     "prompt": "A vase of flowers at a market stall with a person nearby"},
    {"name": "books_shelf_chair",       "prompt": "Books on shelves with a chair and a potted plant in a bookstore"},
    {"name": "apples_oranges_market",   "prompt": "Apples and oranges on display at a farmers market stand"},
    {"name": "person_market_fish",      "prompt": "A person at a market stall holding a knife with a bowl"},
    {"name": "person_clothing_store",   "prompt": "A person standing next to a chair in a clothing store"},
    {"name": "teddy_bears_shelf",       "prompt": "Three teddy bears on a shelf in a toy store"},
    {"name": "donuts_counter_store",    "prompt": "Donuts on a counter at a bakery with a cup nearby"},
    {"name": "chairs_outdoor_cafe",     "prompt": "Two chairs and an umbrella at an outdoor cafe table"},
    {"name": "scissors_tools_shop",     "prompt": "Scissors and a knife on a counter in a hardware store"},
    {"name": "person_bench_gallery",    "prompt": "A person sitting on a bench in an art gallery"},
    {"name": "person_market_stall",     "prompt": "A person at a market stall with a vase and a book"},
    {"name": "person_cheese_counter",   "prompt": "A person behind a counter holding a knife in a cheese shop"},
    {"name": "bottles_wine_shelf",      "prompt": "Three bottles on a wooden shelf in a wine cellar"},
    {"name": "bicycles_sports_store",   "prompt": "Two bicycles in a sports store next to a person"},
    {"name": "person_keyboard_store",   "prompt": "A person playing a keyboard in a music store"},
    {"name": "person_knife_butcher",    "prompt": "A person holding a knife behind a counter in a butcher shop"},
    {"name": "bottles_pharmacy",        "prompt": "Bottles on a pharmacy aisle shelf with a person nearby"},
    {"name": "person_clothing_mirror",  "prompt": "A person standing next to a chair in a vintage clothing store"},
    {"name": "vase_jewellery_case",     "prompt": "A vase next to a display case in a jewellery store"},

    # ── Urban & Street (20) ───────────────────────────────────────────
    {"name": "crosswalk_people_traffic","prompt": "Two people at a crosswalk with a traffic light and a car"},
    {"name": "bicycle_alley_brick",     "prompt": "A bicycle parked in a narrow brick alley"},
    {"name": "train_subway_people",     "prompt": "A train at a platform with two people waiting"},
    {"name": "chairs_rooftop_view",     "prompt": "Two chairs and a potted plant on a rooftop with a city view"},
    {"name": "cars_parking_garage",     "prompt": "Three cars parked in an underground parking garage"},
    {"name": "truck_construction_site", "prompt": "A truck and a person at a construction site"},
    {"name": "traffic_light_night",     "prompt": "A traffic light glowing at a city intersection at night"},
    {"name": "bus_terminal_suitcase",   "prompt": "A bus at a terminal with a person carrying a suitcase"},
    {"name": "people_market_street",    "prompt": "Two people walking through a street market with a stall"},
    {"name": "boat_port_truck",         "prompt": "A boat docked at a port with a truck nearby"},
    {"name": "bench_square_birds",      "prompt": "A bench in a town square with two birds nearby"},
    {"name": "people_bridge_river",     "prompt": "Two people walking on a pedestrian bridge over a river"},
    {"name": "person_skateboard_wall",  "prompt": "A person on a skateboard next to a colorful wall"},
    {"name": "fire_hydrant_building",   "prompt": "A fire hydrant on a sidewalk in front of a brick building"},
    {"name": "bicycles_station",        "prompt": "Three bicycles parked at a docking station on a sidewalk"},
    {"name": "people_stadium_exterior", "prompt": "Two people walking outside a large sports stadium"},
    {"name": "cars_traffic_signs",      "prompt": "Two cars at a junction with a stop sign and a traffic light"},
    {"name": "bicycle_old_town",        "prompt": "A bicycle parked on a cobblestone street with a person nearby"},
    {"name": "people_suitcases_airport","prompt": "Two people with suitcases in an airport hall"},
    {"name": "umbrella_market_square",  "prompt": "An umbrella over a market stall with a person nearby"},

    # ── Special & Miscellaneous (40) ──────────────────────────────────
    {"name": "people_bench_gallery",    "prompt": "Two people on a bench in a museum gallery"},
    {"name": "bed_hospital_room",       "prompt": "A bed and a chair in a hospital room with a clock on the wall"},
    {"name": "scissors_lab_table",      "prompt": "Scissors and a bottle on a table in a science laboratory"},
    {"name": "person_camera_tripod",    "prompt": "A person with a camera on a tripod in a photography studio"},
    {"name": "potted_plants_greenhouse","prompt": "Three potted plants and a bottle in a greenhouse"},
    {"name": "people_concert_stage",    "prompt": "Three people on a concert stage with a keyboard"},
    {"name": "person_camping",          "prompt": "A person sitting on a chair next to a tent in a forest"},
    {"name": "boat_lighthouse",         "prompt": "A boat near a lighthouse on a rocky cliff"},
    {"name": "person_treehouse",        "prompt": "A person sitting in a treehouse in a forest"},
    {"name": "person_balloon_field",    "prompt": "A person standing next to a hot air balloon in a field"},
    {"name": "vase_flowers_shop",       "prompt": "A vase of flowers on a counter in a florist shop"},
    {"name": "person_clay_studio",      "prompt": "A person shaping clay at a table in a ceramic studio"},
    {"name": "cake_birthday_table",     "prompt": "A cake on a dining table with three chairs around it"},
    {"name": "person_violin_street",    "prompt": "A person playing a violin on a city sidewalk"},
    {"name": "people_chess_table",      "prompt": "Two people playing chess at a dining table in a park"},
    {"name": "scissors_fabric_table",   "prompt": "Scissors and fabric on a dining table in a workshop"},
    {"name": "person_telescope_field",  "prompt": "A person looking through a telescope in a field at night"},
    {"name": "people_beach_fire",       "prompt": "Three people sitting around a fire on a sandy beach"},
    {"name": "person_books_library",    "prompt": "A person reading a book in a library with chairs and shelves"},
    {"name": "person_keyboard_hall",    "prompt": "A person playing a keyboard on a stage in a concert hall"},
    {"name": "person_garden_carrot",    "prompt": "A person holding a carrot in a vegetable garden"},
    {"name": "person_dog_park",         "prompt": "A person training a dog in a park"},
    {"name": "fish_aquarium_person",    "prompt": "A person standing next to a large aquarium with fish inside"},
    {"name": "person_beekeeper",        "prompt": "A person in protective gear next to wooden boxes in a garden"},
    {"name": "chairs_outdoor_cinema",   "prompt": "Three chairs facing a large screen in an outdoor cinema"},
    {"name": "person_food_stall",       "prompt": "A person cooking at a food stall in a night market"},
    {"name": "person_hammock_forest",   "prompt": "A person relaxing in a hammock between two trees in a forest"},
    {"name": "cars_drag_race",          "prompt": "Two cars at the start line of a drag race"},
    {"name": "person_market_apples",    "prompt": "A person at a market stall with apples and oranges"},
    {"name": "person_hang_gliding",     "prompt": "A person hang gliding above a green valley"},
    {"name": "books_records_store",     "prompt": "A person looking at books and a chair in a vintage store"},
    {"name": "people_yoga_garden",      "prompt": "Two people sitting on mats in a tropical garden"},
    {"name": "person_surfboard_sunrise","prompt": "A person on a surfboard on calm water at sunrise"},
    {"name": "chairs_cafe_clock",       "prompt": "Two chairs at a dining table in a cafe with a clock on the wall"},
    {"name": "person_snow_outdoors",    "prompt": "A person in a winter coat standing in a snowy backyard"},
    {"name": "elderly_person_park",     "prompt": "An elderly person walking on a path in a park near a bench"},
    {"name": "person_oven_kitchen",     "prompt": "A person standing next to an oven in a home kitchen"},
    {"name": "person_painting_easel",   "prompt": "A person painting on a canvas at an easel in an art studio"},
    {"name": "barista_cup_counter",     "prompt": "A person making coffee with a cup behind a cafe counter"},
    {"name": "child_sports_ball_park",  "prompt": "A child kicking a sports ball in a park"},
]